Mghslh/Areas/Admin/Controllers/AboutUsController.cs
using Mghslh.Core;
using Mghslh.ViewModel.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mghslh.Areas.Admin.Controllers
{
    [Authorize]
    public class AboutUsController : Controller
    {
        // GET: Admin/AboutUs
        public ActionResult Index1()
        {




            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllAboutUs".ExecuParamsSqlOrStored(false).AsList<SettingVM>();
            return View(model);

        }


        public ActionResult Create()
        {
            SettingVM Obj = new SettingVM();

            return View(Obj);
        }
        [HttpPost]
        public JsonResult Create(SettingVM model)
        {

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Uploads/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.Image = "Uploads/Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                }



            }
            var data = "SP_AddAboutUs".ExecuParamsSqlOrStored(false, "Details".KVP(model.Details), "Titel".KVP(model.Titel), "Image".KVP(model.Image), "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {


                return Json("success," + "تم الحفظ", JsonRequestBehavior.AllowGet);


            }
            else

                return Json("error," + "لم يتم الحفظ", JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(int id = 0)
        {

            var model = "SP_SelectAboutUsById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<SettingVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }



        [HttpGet]
        public ActionResult Delete(int id)
        {
            SettingVM obj = new SettingVM();
            obj.Id = id;
            return PartialView("~/Areas/Admin/Views/AboutUs/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteAboutUs".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }

    }
}

Mghslh/Areas/Admin/Views/AboutUs/Create.cshtml
@model Mghslh.ViewModel.ViewModel.SettingVM

@{ 
    Layout = null;

}

@using (Html.BeginForm("Create", "AboutUs", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog modal-lg" style="width:1000px;">
        <div class="modal-content" style="width:1000px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">تفاصيل</h4>
            </div>
            <div class="modal-body" style="width:1000px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">

                                <div class="form-group row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        <label class="control-label">عنوان  </label>
                                    </div>
                                    <div class="col-md-4">
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control" } })*@


                                        <input type="text" class="form-control" id="Titel" name="Titel" value="@Model.Details" />

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        <label class="control-label">تفاصيل  </label>
                                    </div>
                                    <div class="col-md-4">
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control" } })*@


                                        <textarea type="text" class="form-control" id="Details" name="Details" value="@Model.Details">
@Model.Details
</textarea>
                                    </div>
                                </div>








                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.TextBox("file", null, new { @id = "input-1700", @type = "file", @class = "file-loading", @accept = "image/*" })
                                            <script>
                                                $("#input-1700").fileinput({
                                                    maxFileCount: 1,
                                                    allowedFileExtensions: ["jpg", "png", "gif"],
                                                    browseLabel: " إضغط لإختيار صورة ..",
                                                    browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
                                                    browseClass: "btn btn-primary btn-block",
                                                    showCaption: false,
                                                    showRemove: false,
                                                    showUpload: false
                                                });
                                            </script>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-5">

                                    </div>
                                    <div class="col-md-5">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>

                                        <input type="button" value="حفظ" class="btn yellow Saveee" onclick="Save()" />
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>






}








<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

Mghslh/Areas/Admin/Views/AboutUs/Delete.cshtml
@model Mghslh.ViewModel.ViewModel.SettingVM
@{
    Layout = null;

}

<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> حذف  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                </div>
            </div>
        </div>
    </div>
</div>

Mghslh/Areas/Admin/Views/AboutUs/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> الاعلانات</h4>

                    <a id="AddNew" onclick="Create()"  class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxCall/AboutUs.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            AboutUs.init();

        })

    </script>
}

Mghslh/Areas/Admin/Views/AboutUs/Search.cshtml
@model IEnumerable<Mghslh.ViewModel.ViewModel.SettingVM>
    @{ 
        Layout = null;
    }

@if (Model != null)
{


<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                <thead style="background-color:#3bafda;color:white;">
                    <tr>
                        <th>التسلسل</th>
                       
                        <th>تفاصيل </th>
                        <th>الصورة</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>


                        <td>@item.Details</td>
                        <td><img src="~/@item.Image" style="width:150px; height:150px;" /></td>
                        <td>

                            <button type="button" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate" onclick="Edit(@item.Id)"><i class="ti-pencil"></i></button>
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)">  <i class="ti-trash"></i></button>

                        </td>


                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
}
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>